name: Build TinyCore with QEMU Guest Agent
on:
  push:
  pull_request:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Packer
        run: |
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
          sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
          sudo apt-get update && sudo apt-get install packer
      - name: Install QEMU
        run: sudo apt update && sudo apt install -y qemu-utils qemu qemu-kvm
      - name: Run Packer
        run: PACKER_LOG=1 packer build .
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist
          if-no-files-found: error
          path: |
            dist/*.qcow2
      - name: Test image
        run:
          (
            qemu-system-x86_64 \
              -nographic \
              -serial mon:stdio \
              -drive file=dist/tinycore.qcow2,format=qcow2 \
              -monitor telnet::2000,server,nowait >/tmp/qemu.log
          ) &
          sleep 10
          echo 'screendump /tmp/screendump.ppm
          quit' | nc localhost 2000 >/dev/null
          sleep 1
          echo -e "\033[2m"
          cat /tmp/qemu.log
          echo -e "\033[0m"